plugins {
    id 'com.android.application'
}

def stableKeystorePath = System.getenv('LANCAST_KEYSTORE_PATH')

android {
    compileSdk 33
    buildToolsVersion '33.0.2'

    signingConfigs {
        if (stableKeystorePath) {
            stable {
                storeFile file(stableKeystorePath)
                storePassword System.getenv('LANCAST_KEYSTORE_PASSWORD')
                keyAlias System.getenv('LANCAST_KEY_ALIAS')
                keyPassword System.getenv('LANCAST_KEY_PASSWORD')
            }
        }
    }

    defaultConfig {
        applicationId 'com.lancast.sender'
        minSdk 21
        targetSdk 28
        versionCode 10
        versionName '4.8.0'
    }

    buildTypes {
        debug {
            if (stableKeystorePath) {
                signingConfig signingConfigs.stable
            }
        }
    }
}
